export default {
  PRODUCTLIST: 'ProductList',
  CART: 'Cart',
  SIDEBARAPP: 'SideBarApp',
  WINTERCAT: 'WinterCat',
  SUMMERCAT: 'SummerCat',
  SUBCATEGORY: 'SubCategory',
  WISHLIST: 'Wishlist',
  ADDRESS: 'Address',
  SAVEDADDRESS: 'SavedAddress',

  SCREENTITLE: {
    PRODUCTLIST: 'Product List',
    CART: 'Cart',
    SUMMER: 'Summer',
    WINTER: 'Winter',
    CAP: 'Cap',
    KURTA: 'Kurta',
    PANTS: 'Pant',
    SHIRT: 'Shirt',
    SUNGLASSES: 'sunglasses',
    TSHIRT: 't-shirt',
    JACKET: 'Jacket',
    PAJAMA: 'pajama',
    SHOES: 'Shoes',
    SWEATER: 'Sweater',
    WISHLIST: 'Wishlist',
    ADDRESS: 'Address',
  },
  CONSTANTMSG: {
    NOPRODUCT: 'Products Not Available',
    NODATA: 'Products not added',
    NO_PRODUCT_WISHLIST: 'No products in wishlist',
    REMOVE_ALERT_FOR_CART: 'Do you want to remove this product?',
    REMOVE_ALERT_FOR_WISHLIST: 'Remove this product from wishlist',
  },
  CONSTANTHEADINGS: {
    CATEGORY: 'Category: ',
    DESCRIPTION: 'Desciption:',
    QUANTITY: 'Quantity: ',
    RS: 'Rs: ',
    TOTALPRICE: 'Total Price:',
    FASHION: 'Fashion',
    ADDRESS: 'Add Address',
    ADD_ADDRESS: 'Please add your address',
    ADDRESS_TYPE: 'Address Type',
    SAVED_LOCATION: 'Saved Location',
  },
  BUTTONTITLE: {
    ADDED: 'Added',
    ADDTOCART: 'Add to cart',
    HOME: 'HOME',
    WORK: 'WORK',
    SAVE: 'SAVE',
    CANCEL: 'CANCEL',
    SAVED_ADDRESS: 'Saved Address',
    ADD_NEW: 'ADD NEW',
    CONTINUE: 'CONTINUE',
  },
  PLACEHOLDERS: {
    NAME: 'Full name',
    CONTACT: '10 - digit mobile number',
    PINCODE: 'Pincode',
    LOCALITY:'Locality',
    ADDRESS_PLACEHOLDER: 'Address (Area and Street)',
    CITY: 'City/District/Town',
    STATE: 'Select state',
    LANDMARK: 'Landmark',
    ALTERNATIVE:'Alternative phone (Optional)'
  },
  TEXTFIELDTITLE: {
    FULL_NAME: 'Full Name',
    MOBILE: 'Contact',
    CITY_TITLE: 'City',
    STATE_TITLE: 'State',
  },
  ALERT_MESSAGES: {
    NAME: 'invalid name',
    CONTACT: 'invalid contact',
    PIN: 'invalid pin',
    LOCALITY: 'invalid Locality',
    ADDRESS: 'invalid Address',
    CITY: 'invalid city name',
    LANDMARK: 'invalid landmark',
    STATE: 'Please select state',
    SAVED: 'Form saved',
    CANCEL: 'CANCEL',
    OK: 'OK',
  },
  VALIDATION: {
    VALIDATE_NAME: /[a-zA-Z][a-zA-Z ]{2,}/, 
    VALIDATE_CONTACT: /^[0]?[789]\d{9}$/,
    VALIDATE_PINCODE: /^[0-9]{6}$/,
  }
};
